<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<iframe src="https://www.youtube.com/watch?v=2Vx8TDX6VVA" width="100%" height="100%"></iframe>

    <iframe width="560" height="315" src="https://drive.google.com/file/d/1Rf3dOMq282-i1TQoeqrVJAsN6fVxkJOU/view?usp=sharing" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</body>
</html>